name: health_tracker_app
description: "A Flutter Health Tracker App (Langkah, Tidur, dan Asupan Makanan)"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # --- Core dependencies ---
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  dio: ^5.9.0

  # --- UI & grafik tambahan ---
  google_fonts: ^6.1.0          # Font modern (Poppins, Inter, dll)
  fl_chart: ^0.68.0             # Grafik langkah dan tidur
  percent_indicator: ^4.2.3     # Lingkaran progress untuk langkah
  pedometer: ^4.0.1             # Plugin sensor langkah (Android/iOS)
  intl: ^0.19.0                 # Format tanggal dan angka

  # --- (opsional) animasi dan icon tambahan ---
  lottie: ^3.1.0                # Animasi ringan (misal loading)
  font_awesome_flutter: ^10.7.0 # Icon kesehatan, tidur, makanan

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Jika kamu nanti menambah aset gambar atau ikon, aktifkan ini:
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # Jika kamu punya font custom, bisa tambahkan di sini:
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
